# Generated by Django 5.2.8 on 2025-12-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='pos_x',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='pos_y',
            field=models.IntegerField(default=100),
        ),
    ]
