# Generated by Django 5.2.8 on 2025-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_imagepost_pos_x_imagepost_pos_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='width',
            field=models.IntegerField(default=200),
        ),
    ]
