# Generated by Django 5.1.2 on 2026-01-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_imagepost_height_imagepost_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='pos_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='pos_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
