# Generated by Django 5.1.2 on 2026-05-11 16:01

import boards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_imagepost_height_alter_imagepost_pos_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='pos_x',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='pos_y',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='width',
            field=models.IntegerField(default=200),
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to=boards.models.background_upload_to)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
