# Generated by Django 5.1.2 on 2026-05-11 21:50

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='background',
            field=models.ImageField(default='Gallery_texture.jpg', upload_to=boards.models.background_upload_to),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(default='default_profile_image.png', upload_to=boards.models.profile_upload_to),
        ),
    ]
